server:
  port: 9999
spring:
  application:
    name: order-platform
  profiles:
    active: dev
  datasource:
    platform: postgres
    url: jdbc:h2:mem:order-platform-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true
    username: login
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    url: ${spring.datasource.url}
    contexts: prod

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

dev:
  user-count: 5
  product-count: 5
